import type { Metadata } from "next";
import "./globals.css";
import AppWrapper from "./appWrapper";

export const metadata: Metadata = {
  title: "AutoTranscriber",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <AppWrapper>
    {children}
  </AppWrapper>;
}
